/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomStatus = IDL.Variant({
  'finished' : IDL.Null,
  'waiting' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const RoomCode = IDL.Text;
export const PlaceId = IDL.Nat;
export const Score = IDL.Nat;
export const Guess = IDL.Record({
  'player' : IDL.Principal,
  'text' : IDL.Text,
  'score' : Score,
});
export const RoundView = IDL.Record({
  'place' : PlaceId,
  'guesses' : IDL.Vec(Guess),
});
export const RoomView = IDL.Record({
  'status' : RoomStatus,
  'currentRound' : IDL.Nat,
  'code' : RoomCode,
  'host' : IDL.Principal,
  'roundScores' : IDL.Vec(RoundView),
  'players' : IDL.Vec(IDL.Principal),
  'totalRounds' : IDL.Nat,
});
export const GameError = IDL.Variant({
  'notInRoom' : IDL.Null,
  'alreadyInRoom' : IDL.Null,
  'notHost' : IDL.Null,
  'invalidGuess' : IDL.Null,
  'gameNotStarted' : IDL.Null,
  'roundNotActive' : IDL.Null,
  'notSignedIn' : IDL.Null,
  'roomNotFound' : RoomCode,
  'roomFull' : IDL.Null,
  'gameAlreadyStarted' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : RoomView, 'err' : GameError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Place = IDL.Record({
  'id' : PlaceId,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'name' : IDL.Text,
  'aliases' : IDL.Vec(IDL.Text),
});
export const Result_2 = IDL.Variant({ 'ok' : Place, 'err' : GameError });
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'totalScore' : Score,
});
export const PlayerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'bestScore' : Score,
  'totalScore' : Score,
});
export const Result_1 = IDL.Variant({
  'ok' : PlayerProfile,
  'err' : GameError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_3], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Nat], [Result], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentRoundPlace' : IDL.Func([RoomCode], [Result_2], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getProfile' : IDL.Func([], [Result_1], ['query']),
  'getRoomState' : IDL.Func([RoomCode], [Result], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([RoomCode], [Result], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setDisplayName' : IDL.Func([IDL.Text], [Result_1], []),
  'startGame' : IDL.Func([RoomCode], [Result], []),
  'submitGuess' : IDL.Func([RoomCode, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomStatus = IDL.Variant({
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const RoomCode = IDL.Text;
  const PlaceId = IDL.Nat;
  const Score = IDL.Nat;
  const Guess = IDL.Record({
    'player' : IDL.Principal,
    'text' : IDL.Text,
    'score' : Score,
  });
  const RoundView = IDL.Record({
    'place' : PlaceId,
    'guesses' : IDL.Vec(Guess),
  });
  const RoomView = IDL.Record({
    'status' : RoomStatus,
    'currentRound' : IDL.Nat,
    'code' : RoomCode,
    'host' : IDL.Principal,
    'roundScores' : IDL.Vec(RoundView),
    'players' : IDL.Vec(IDL.Principal),
    'totalRounds' : IDL.Nat,
  });
  const GameError = IDL.Variant({
    'notInRoom' : IDL.Null,
    'alreadyInRoom' : IDL.Null,
    'notHost' : IDL.Null,
    'invalidGuess' : IDL.Null,
    'gameNotStarted' : IDL.Null,
    'roundNotActive' : IDL.Null,
    'notSignedIn' : IDL.Null,
    'roomNotFound' : RoomCode,
    'roomFull' : IDL.Null,
    'gameAlreadyStarted' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : RoomView, 'err' : GameError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Place = IDL.Record({
    'id' : PlaceId,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'name' : IDL.Text,
    'aliases' : IDL.Vec(IDL.Text),
  });
  const Result_2 = IDL.Variant({ 'ok' : Place, 'err' : GameError });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'totalScore' : Score,
  });
  const PlayerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'bestScore' : Score,
    'totalScore' : Score,
  });
  const Result_1 = IDL.Variant({ 'ok' : PlayerProfile, 'err' : GameError });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_3], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Nat], [Result], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentRoundPlace' : IDL.Func([RoomCode], [Result_2], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getProfile' : IDL.Func([], [Result_1], ['query']),
    'getRoomState' : IDL.Func([RoomCode], [Result], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([RoomCode], [Result], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setDisplayName' : IDL.Func([IDL.Text], [Result_1], []),
    'startGame' : IDL.Func([RoomCode], [Result], []),
    'submitGuess' : IDL.Func([RoomCode, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };