/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type GameError = { 'notInRoom' : null } |
  { 'alreadyInRoom' : null } |
  { 'notHost' : null } |
  { 'invalidGuess' : null } |
  { 'gameNotStarted' : null } |
  { 'roundNotActive' : null } |
  { 'notSignedIn' : null } |
  { 'roomNotFound' : RoomCode } |
  { 'roomFull' : null } |
  { 'gameAlreadyStarted' : null };
export interface Guess {
  'player' : Principal,
  'text' : string,
  'score' : Score,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'displayName' : string,
  'totalScore' : Score,
}
export interface Place {
  'id' : PlaceId,
  'lat' : number,
  'lng' : number,
  'name' : string,
  'aliases' : Array<string>,
}
export type PlaceId = bigint;
export interface PlayerProfile {
  'principal' : Principal,
  'displayName' : string,
  'gamesPlayed' : bigint,
  'bestScore' : Score,
  'totalScore' : Score,
}
export type Result = { 'ok' : RoomView } |
  { 'err' : GameError };
export type Result_1 = { 'ok' : PlayerProfile } |
  { 'err' : GameError };
export type Result_2 = { 'ok' : Place } |
  { 'err' : GameError };
export type Result_3 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type RoomCode = string;
export type RoomStatus = { 'finished' : null } |
  { 'waiting' : null } |
  { 'inProgress' : null };
export interface RoomView {
  'status' : RoomStatus,
  'currentRound' : bigint,
  'code' : RoomCode,
  'host' : Principal,
  'roundScores' : Array<RoundView>,
  'players' : Array<Principal>,
  'totalRounds' : bigint,
}
export interface RoundView { 'place' : PlaceId, 'guesses' : Array<Guess> }
export type Score = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_3>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[bigint], Result>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRoundPlace' : ActorMethod<[RoomCode], Result_2>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getProfile' : ActorMethod<[], Result_1>,
  'getRoomState' : ActorMethod<[RoomCode], Result>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[RoomCode], Result>,
  'schema' : ActorMethod<[], string>,
  'setDisplayName' : ActorMethod<[string], Result_1>,
  'startGame' : ActorMethod<[RoomCode], Result>,
  'submitGuess' : ActorMethod<[RoomCode, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];